### ISSUE TITLE
the goo dispenser doesn't dispense goo

### ISSUE THREAD

**Issue by smotanove** [MarxMustermann/OfMiceAndMechs#10]
In the first room there is a goo dispenser. I would expect if I interact (`j`) with it, that it would do it's thing, which intuitively would be dispensing goo. It should at least say something. If it first tells me after running it, that I can `j` it and then I can't it's frustrating.

PS: You owe me some goo.

**Comment by MarxMustermann** [comment]
thats actually not true^^

The goo dispenser was ment to be like a soda refill at a restaurant. You fill up you bottle with it, if the amount of charges run low. I tested and it works it it sets your bottles contents back to 100. I just doesn't tell you.

I'll take this issue as "print some message when goo dispenser" and still treat it as a bug.
