### ISSUE TITLE
pygame doesn't load own window?

### ISSUE THREAD

**Issue by smotanove** [MarxMustermann/OfMiceAndMechs#7]
So, there's a separate window, but it's not doing anything so far. And the game itself seems to load in the shell, just like without `-t`:

![pygame](https://i.imgur.com/bE7jW9t.png)

**Comment by MarxMustermann** [comment]
The pygame window does indeed look like described. The has the reason it can render the terrain only. So text, selections and cutscenes don't work. The workaround is to use the shell for text and the pygame for the gamefield. The pygame window does take keyboard input and shows the same game as the shell does.

As you might have guessed the tile based mode is not production ready. I will address this when i clean up the tile based window.

**Comment by MarxMustermann** [comment]
cutscenes are rendered in tilebased mode now :-)
