### ISSUE TITLE
undo or go-back button

### ISSUE THREAD

**Issue by smotanove** [MarxMustermann/OfMiceAndMechs#8]
I just happened to misclick and the dialogue continued without any option to go back.

**Comment by MarxMustermann** [comment]
I will have to think about this. Taking back moves as such is not intended and may not be possible. 

For cutscenes or dialog it is way to easy to misclick and to have stuff scroll. Also chat option do have direct effect on the gamestate to this might count as taking back a move. On selections with catastrophical  
impact a misclick protection like asking for confimations may be a solution.

I think i will probably close this as wontfix someday, but maybe some solution comes up. So if you have any ideas ;-)
