### ISSUE TITLE
hotkey confusion

### ISSUE THREAD

**Issue by smotanove** [MarxMustermann/OfMiceAndMechs#9]
Either the tutorial needs to redo the hotkey lessons a few times that one can remember or one needs a way to look them up again. After just playing 5 mins I think I've learned j,k,J,e. It would also be cool if the keys would be related. Like `e - examine` makes sense, but why is pickup `k`?

**Comment by smotanove** [comment]
I found there is a help. Nice! I just didn't look towards the bottom line and read all of that carefully. I guess in the beginning it's a little information overload.

**Comment by MarxMustermann** [comment]
yeah, is some overload and i am open for suggestions on how to tweak the GUI.

Also the idea with the keybindings is not to have an shortcut based layout, but a ergonomical layout

So for the right fingers it is hjkl+guiopbnm and for the left hand it is wasd+eqr. If you prefer an easy to remember or vim controls you can edit config/commandChars.py. 

If you have made an alternative layout, please submit it as issue or pull request.

 (? is the default key for help)
